#!/bin/bash
# grab-agent installer for Linux / macOS
# Usage: bash install-linux.sh

set -e

LOG_DIR="$HOME/.grab"
AGENT_LOG="$LOG_DIR/agent.log"
CF_LOG="$LOG_DIR/cloudflare.log"
INSTALL_BIN="$HOME/.local/bin"
ENV_FILE="$LOG_DIR/.env"

# ── Colours ───────────────────────────────────────────────────────────────────
R="\033[31m"; G="\033[32m"; Y="\033[33m"; C="\033[36m"; B="\033[1m"; RST="\033[0m"
ok()   { echo -e "  ${G}✓${RST} $1"; }
err()  { echo -e "  ${R}✗${RST} $1"; exit 1; }
info() { echo -e "  ${C}·${RST} $1"; }
hdr()  { echo -e "\n${B}${C}  $1${RST}\n  $(printf '─%.0s' $(seq 1 ${#1}))"; }

hdr "grab-agent installer (Linux / macOS)"
mkdir -p "$LOG_DIR" "$INSTALL_BIN"

# ── Detect OS / package manager ───────────────────────────────────────────────
if [[ "$OSTYPE" == "darwin"* ]]; then
    PKG_INSTALL="brew install"
elif command -v apt-get &>/dev/null; then
    PKG_INSTALL="sudo apt-get install -y"
elif command -v dnf &>/dev/null; then
    PKG_INSTALL="sudo dnf install -y"
elif command -v pacman &>/dev/null; then
    PKG_INSTALL="sudo pacman -S --noconfirm"
else
    err "Unsupported OS. Install python3 and ffmpeg manually then re-run."
fi

# ── Python ────────────────────────────────────────────────────────────────────
hdr "Checking Python"
if command -v python3 &>/dev/null; then
    ok "Python found: $(python3 --version 2>&1)"
else
    info "Installing Python…"
    $PKG_INSTALL python3 || err "Failed to install Python"
    ok "Python installed"
fi

# ── ffmpeg ────────────────────────────────────────────────────────────────────
hdr "Checking ffmpeg"
if command -v ffmpeg &>/dev/null; then
    ok "ffmpeg already installed"
else
    info "Installing ffmpeg…"
    $PKG_INSTALL ffmpeg || err "Failed to install ffmpeg"
    ok "ffmpeg installed"
fi

# ── cloudflared ───────────────────────────────────────────────────────────────
hdr "Checking cloudflared"
if command -v cloudflared &>/dev/null; then
    ok "cloudflared already installed"
else
    info "Installing cloudflared…"
    ARCH=$(uname -m)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install cloudflared
    elif [[ "$ARCH" == "x86_64" ]]; then
        curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64" \
            -o "$INSTALL_BIN/cloudflared"
        chmod +x "$INSTALL_BIN/cloudflared"
    elif [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
        curl -fsSL "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64" \
            -o "$INSTALL_BIN/cloudflared"
        chmod +x "$INSTALL_BIN/cloudflared"
    else
        err "Unknown arch: $ARCH — download cloudflared manually from https://github.com/cloudflare/cloudflared/releases"
    fi
    export PATH="$INSTALL_BIN:$PATH"
    ok "cloudflared installed"
fi

# ── Install agent.py ──────────────────────────────────────────────────────────
hdr "Installing grab-agent"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$SCRIPT_DIR/agent.py" ]; then
    cp "$SCRIPT_DIR/agent.py" "$INSTALL_BIN/grab-agent"
    ok "Copied agent.py from local directory"
else
    info "Downloading agent.py…"
    curl -fsSL "https://raw.githubusercontent.com/yusuf-bot/grab/main/client/agent.py" \
        -o "$INSTALL_BIN/grab-agent" \
        || err "Failed to download agent.py — place agent.py next to this script and retry"
    ok "Downloaded agent.py"
fi

chmod +x "$INSTALL_BIN/grab-agent"

if [[ ":$PATH:" != *":$INSTALL_BIN:"* ]]; then
    echo "export PATH=\"$INSTALL_BIN:\$PATH\"" >> "$HOME/.bashrc"
    export PATH="$INSTALL_BIN:$PATH"
    info "Added $INSTALL_BIN to PATH in ~/.bashrc"
fi
ok "grab-agent installed → $INSTALL_BIN/grab-agent"

# ── Create .env config ────────────────────────────────────────────────────────
hdr "Configuration"

SKIP_ENV=""
if [ -f "$ENV_FILE" ]; then
    ok "Found existing config at $ENV_FILE"
    read -rp "  Overwrite it? [y/N] " OVERWRITE
    [[ "$OVERWRITE" =~ ^[Yy]$ ]] || SKIP_ENV=1
fi

if [ -z "$SKIP_ENV" ]; then
    DEFAULT_OUT="$HOME/Downloads"
    echo ""
    read -rp "  Output dir [$DEFAULT_OUT]: " CUSTOM_OUT
    OUTPUT_DIR="${CUSTOM_OUT:-$DEFAULT_OUT}"

    read -rp "  Agent port [9090]: " CUSTOM_PORT
    AGENT_PORT="${CUSTOM_PORT:-9090}"

    cat > "$ENV_FILE" << ENVEOF
# grab agent config — generated by install-linux.sh
AGENT_PORT=$AGENT_PORT
OUTPUT_DIR=$OUTPUT_DIR
ENVEOF
    ok "Config saved → $ENV_FILE"
else
    source "$ENV_FILE" 2>/dev/null || true
    OUTPUT_DIR="${OUTPUT_DIR:-$HOME/Downloads}"
    AGENT_PORT="${AGENT_PORT:-9090}"
    ok "Using existing config (port=$AGENT_PORT, out=$OUTPUT_DIR)"
fi

mkdir -p "$OUTPUT_DIR"

# ── Stop any existing instances ───────────────────────────────────────────────
hdr "Stopping existing instances"
pkill -f grab-agent  2>/dev/null && info "Stopped old grab-agent"  || true
pkill -f cloudflared 2>/dev/null && info "Stopped old cloudflared" || true
sleep 1
ok "Clean slate"

# ── Start grab-agent ──────────────────────────────────────────────────────────
hdr "Starting grab-agent"
nohup env OUTPUT_DIR="$OUTPUT_DIR" AGENT_PORT="$AGENT_PORT" \
    "$INSTALL_BIN/grab-agent" > "$AGENT_LOG" 2>&1 &
AGENT_PID=$!
sleep 2

if kill -0 "$AGENT_PID" 2>/dev/null; then
    ok "grab-agent running (PID $AGENT_PID) on port $AGENT_PORT"
    ok "Output → $OUTPUT_DIR"
else
    err "grab-agent failed to start. Check: cat $AGENT_LOG"
fi

# ── Start cloudflared tunnel ──────────────────────────────────────────────────
hdr "Starting Cloudflare tunnel"
info "Requesting tunnel URL… (takes ~10s)"
nohup cloudflared tunnel --url "http://localhost:$AGENT_PORT" \
    > "$CF_LOG" 2>&1 &

CF_URL=""
for i in $(seq 1 30); do
    sleep 1
    CF_URL=$(grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' "$CF_LOG" 2>/dev/null | head -1)
    [ -n "$CF_URL" ] && break
    printf "."
done
echo ""

[ -z "$CF_URL" ] && err "Cloudflare tunnel failed. Check: cat $CF_LOG"
ok "Tunnel active: $CF_URL"
echo "$CF_URL" > "$LOG_DIR/tunnel_url.txt"

# ── Auto-start ────────────────────────────────────────────────────────────────
hdr "Setting up auto-start"

if [[ "$OSTYPE" == "darwin"* ]]; then
    PLIST_DIR="$HOME/Library/LaunchAgents"
    mkdir -p "$PLIST_DIR"

    cat > "$PLIST_DIR/com.grab.agent.plist" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.grab.agent</string>
  <key>ProgramArguments</key><array><string>$INSTALL_BIN/grab-agent</string></array>
  <key>EnvironmentVariables</key><dict>
    <key>OUTPUT_DIR</key><string>$OUTPUT_DIR</string>
    <key>AGENT_PORT</key><string>$AGENT_PORT</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
PLISTEOF

    cat > "$PLIST_DIR/com.grab.cloudflared.plist" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.grab.cloudflared</string>
  <key>ProgramArguments</key><array>
    <string>$(which cloudflared)</string>
    <string>tunnel</string><string>--url</string>
    <string>http://localhost:$AGENT_PORT</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
</dict></plist>
PLISTEOF

    launchctl load "$PLIST_DIR/com.grab.agent.plist"       2>/dev/null || true
    launchctl load "$PLIST_DIR/com.grab.cloudflared.plist" 2>/dev/null || true
    ok "launchd services registered — auto-starts on login"

elif command -v systemctl &>/dev/null; then
    SYSDIR="$HOME/.config/systemd/user"
    mkdir -p "$SYSDIR"

    cat > "$SYSDIR/grab-agent.service" << SVCEOF
[Unit]
Description=grab agent
After=network.target

[Service]
Environment=OUTPUT_DIR=$OUTPUT_DIR
Environment=AGENT_PORT=$AGENT_PORT
ExecStart=$INSTALL_BIN/grab-agent
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
SVCEOF

    cat > "$SYSDIR/grab-cloudflared.service" << SVCEOF
[Unit]
Description=grab cloudflared tunnel
After=grab-agent.service

[Service]
ExecStart=$(which cloudflared) tunnel --url http://localhost:$AGENT_PORT
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
SVCEOF

    systemctl --user daemon-reload
    systemctl --user enable grab-agent grab-cloudflared 2>/dev/null || true
    ok "systemd services enabled — auto-starts on login"

else
    grep -q "grab-agent" "$HOME/.bashrc" 2>/dev/null || \
        echo "nohup env OUTPUT_DIR=$OUTPUT_DIR AGENT_PORT=$AGENT_PORT grab-agent > $AGENT_LOG 2>&1 & nohup cloudflared tunnel --url http://localhost:$AGENT_PORT > $CF_LOG 2>&1 &" \
        >> "$HOME/.bashrc"
    ok "Added to ~/.bashrc — starts when you open a terminal"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${B}${G}  ✓ All done!${RST}"
echo ""
echo -e "  ${B}Agent URL (paste into the web UI dot menu):${RST}"
echo -e "  ${C}${B}  $CF_URL${RST}"
echo ""
echo -e "  To get this URL anytime:  ${C}cat $LOG_DIR/tunnel_url.txt${RST}"
echo -e "  Config file:              ${C}$ENV_FILE${RST}"
echo ""